CREATE TABLE "all-seeing-eye_insight" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "all-seeing-eye_insight_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(500) NOT NULL,
	"content" text NOT NULL,
	"date" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "all-seeing-eye_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"firstName" varchar(255),
	"lastName" varchar(255),
	"profileImageUrl" varchar(512),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "all-seeing-eye_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "all-seeing-eye_insight" ADD CONSTRAINT "insight_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."all-seeing-eye_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "all-seeing-eye_insight" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "date_idx" ON "all-seeing-eye_insight" USING btree ("date");--> statement-breakpoint
CREATE INDEX "email_idx" ON "all-seeing-eye_user" USING btree ("email");