CREATE TABLE "all-seeing-eye_alert_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "all-seeing-eye_alert_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruleId" integer NOT NULL,
	"newsId" varchar(255),
	"context" text,
	"message" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "all-seeing-eye_alert_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "all-seeing-eye_alert_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255),
	"ruleText" text NOT NULL,
	"ruleType" varchar(32) NOT NULL,
	"params" json NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "all-seeing-eye_insight" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "all-seeing-eye_insight" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "all-seeing-eye_insight" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "all-seeing-eye_insight_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "all-seeing-eye_alert_event" ADD CONSTRAINT "alert_event_rule_id_fk" FOREIGN KEY ("ruleId") REFERENCES "public"."all-seeing-eye_alert_rule"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "all-seeing-eye_alert_event" ADD CONSTRAINT "alert_event_news_id_fk" FOREIGN KEY ("newsId") REFERENCES "public"."all-seeing-eye_news"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "all-seeing-eye_alert_rule" ADD CONSTRAINT "alert_rule_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."all-seeing-eye_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "alert_event_rule_id_idx" ON "all-seeing-eye_alert_event" USING btree ("ruleId");--> statement-breakpoint
CREATE INDEX "alert_event_news_id_idx" ON "all-seeing-eye_alert_event" USING btree ("newsId");--> statement-breakpoint
CREATE INDEX "alert_rule_user_id_idx" ON "all-seeing-eye_alert_rule" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "alert_rule_type_idx" ON "all-seeing-eye_alert_rule" USING btree ("ruleType");--> statement-breakpoint
CREATE INDEX "alert_rule_active_idx" ON "all-seeing-eye_alert_rule" USING btree ("active");